Vagrant.configure("2") do |config|

  config.vm.define :router do |router|
    router.vm.box = "debian/bullseye64"
    router.vm.hostname = "router"
    router.vm.synced_folder ".", "/vagrant", disabled: true
    router.vm.network :public_network,
    :dev => "br0",
    :mode => "bridge",
    :type => "bridge"
    router.vm.network :private_network,
      :libvirt__network_name => "red1",
      :libvirt__dhcp_enabled => false,
      :ip => "10.0.0.11",
      :libvirt__forward_mode => "veryisolated"
    config.vm.provision "ansible_local" do |ansible|    ansible.playbook = "/ansible/site.yml"
  end
  end


  config.vm.define :cliente do |cliente|
    cliente.vm.box = "debian/bullseye64"
    cliente.vm.hostname = "cliente"
    cliente.vm.synced_folder ".", "/vagrant", disabled: true
    cliente.vm.network :private_network,
      :libvirt__network_name => "red1",
      :libvirt__dhcp_enabled => false,
      :ip => "10.0.0.12",
      :libvirt__forward_mode => "veryisolated"
     config.vm.provision "ansible_local" do |ansible|    ansible.playbook = "/ansible/site.yml"
 end
 end
end
