- name: cambiar configuración de red
  template:
    src: etc/network/interfaces
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: 0644
  notify:
    - reiniciar la máquina

